"""empty message

Revision ID: b41ace1ffeb4
Revises: db3b61ae60c7
Create Date: 2020-11-29 13:05:37.589237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41ace1ffeb4'
down_revision = 'db3b61ae60c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bucketlist_item_name_key', 'bucketlist_item', type_='unique')
    op.drop_constraint('bucketlists_name_key', 'bucketlists', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('bucketlists_name_key', 'bucketlists', ['name'])
    op.create_unique_constraint('bucketlist_item_name_key', 'bucketlist_item', ['name'])
    # ### end Alembic commands ###
