"""empty message

Revision ID: cae5532006dc
Revises: 484894779f2c
Create Date: 2020-11-17 13:05:04.310548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae5532006dc'
down_revision = '484894779f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bucketlists', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bucketlists', type_='unique')
    # ### end Alembic commands ###
